version: "3.8"
services:
    frontend:
        image: node:14.18.1-alpine
        working_dir: /home/node/app
        ports:
            - "5000:5000"
        volumes:
            - ./services/frontend:/home/node/app
        user: ${UID}:${GID}
        environment:
            NPM_CONFIG_CACHE: /home/node/app/.npm-cache-docker
        entrypoint: ["npm"]
        command: ["run", "dev"]
