version: "3.8"
services:
    frontend:
        image: node:14.18.1-alpine
        working_dir: /home/node/app
        ports:
            - "5000:5000"
            - "35729:35729"
        volumes:
            - ./services/frontend:/home/node/app
        user: ${UID}:${GID}
        environment:
            NPM_CONFIG_CACHE: /home/node/app/.npm-cache-docker
            HRRR_XSECTION_API: "http://localhost:8000/api"
        entrypoint: ["npm"]
        command: ["run", "dev"]

    api:
        build: services/api
        image: api
        user: ${UID}:${GID}
        ports:
            - "8000:8000"
        volumes:
            - ./services/api:/usr/src/app
            - ./notebooks/data/:/data
        environment:
            HRRR_DATA_DIR: "/data/grib2/"
            FORECASTS_ARRAY: "/data/wrfnat.zarr"
            FLASK_ENV: "development"
