version: "3.8"
services:
    frontend:
        image: node:14.18.1-alpine
        working_dir: /home/node/app
        ports:
            - "5000:5000"
        volumes:
            - ./services/frontend:/home/node/app
        user: ${UID}:${GID}
        environment:
            NPM_CONFIG_CACHE: /home/node/app/.npm-cache-docker
            HRRR_XSECTION_API: "http://localhost:9000/xsection/"
        entrypoint: ["npm"]
        command: ["run", "dev"]

    proxy:
        image: nginx:latest
        ports:
            - "9000:9000"
        volumes:
            - ./dev-proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro

    xsection:
        build: services/xsection
        image: gsl-atd-smoke-vis:latest
        user: ${UID}:${GID}
        environment:
            HRRR_SMOKE_BUCKET: "gsl-atd-smoke-vis"
